[COMMON]
packages.arch = [
  'linux-zen', 'linux-firmware', 'sbctl',
  'base', 'base-devel', 'iptables-nft', 'udisks2', 'rng-tools', 'zram-generator', 'btrfs-progs', 'bash-completion', 'openssh', 'git', 'git-lfs', 'ntfs-3g', 'cifs-utils', 'openldap', 'sssd', 'devtools',
  'helix', 'bash-language-server', 'marksman', 'taplo-cli', 'texlab', 'python-lsp-server', 'vscode-css-languageserver', 'vscode-json-languageserver', 'yaml-language-server', 'typescript-language-server',
  'btop', 'tmux', 'zsh', 'zsh-completions', 'zsh-autosuggestions', 'zsh-syntax-highlighting', 'zsh-history-substring-search', 'compsize', 'dust', 'rsync', 'man', 'tealdeer', 'ripgrep', 'fzf', 'atuin',
  'noto-fonts', 'noto-fonts-cjk', 'noto-fonts-emoji', 'inter-font', 'ttc-iosevka',
  'tailscale', 'nix', 'yarn', 'ethtool', 'python-pip'
]
packages.archExtra = [
  'bc', 'usbutils', 'hyfetch', 'img2pdf', 'syncthing', 'keepassxc', 'nvtop',
  'pipewire', 'wireplumber', 'pipewire-alsa', 'pipewire-pulse', 'libpulse', 'alsa-utils', 'playerctl',
  'mesa', 'lib32-mesa', 'libva-mesa-driver', 'libva-utils', 'vulkan-tools', 'blas-openblas',
  'ly', 'hyprland', 'hypridle', 'hyprpaper', 'hyprlock', 'waybar', 'mako', 'xdg-desktop-portal-hyprland', 'xdg-desktop-portal-gtk', 'rofi-wayland', 'cliphist', 'polkit-gnome', 'power-profiles-daemon', 'qt6ct', 'alacritty', 'grim', 'slurp', 'nautilus', 'ffmpegthumbnailer', 'gvfs', 'gvfs-mtp', 'ttf-nerd-fonts-symbols', 'gammastep',
  'fcitx5-im', 'fcitx5-mozc', 'fcitx5-chewing', 'fcitx5-chinese-addons', 'fcitx5-pinyin-zhwiki',
  'texlive-binextra', 'texlive-langchinese', 'texlive-langjapanese', 'texlive-latexextra', 'texlive-luatex', 'texlive-mathscience', 'texlive-plaingeneric',
  'firefox', 'profile-sync-daemon', 'mpv', 'zathura', 'zathura-pdf-poppler', 'jupyterlab', 'gnuplot',
  'loupe', 'gimp', 'obs-studio', 'steam', 'lutris', 'telegram-desktop', 'discord', 'meld'
] # chntpw (Windows Registry), efibootmgr, fswebcam, p7zip, unrar, innoextract, iperf3, nethogs, nmap, nvme-cli, picocom, powertop, python-sympy, speedtest-cli, torbrowser-launcher, traceroute, tree, wev
packages.AUR = [
  'paru', 'sing-box', 'yazi', 'cmake-language-server', 'moonlight-qt', 'ltex-ls-bin', 'carapace', 'nil-git'
]
packages.AURExtra = [
  'anki', 'protontricks', 'fcitx5-pinyin-moegirl', 'xdg-terminal-exec-git', 'wluma'
]
packages.archIgnores = []
mainUser = 'proteus'
aurChrootPath = '/tmp/aur_chroot'

[PROTEUSLAPTOP]
installExtra = true
packagesSpec = [
  'bluez', 'bluez-utils', 'iwd', 'wireless-regdb', 'blueman', 'bolt', 'hip-runtime-amd', 'rocm-smi-lib',
  'amd-ucode', 'vulkan-radeon', 'lib32-vulkan-radeon', 'mpd', 'mpc', 'keepassxc', 'blender', 'ario', 'yt-dlp', 'ytfzf', 'docker', 'act', 'bat', 'colord', 'ddcutil', 'libc++', 'lld', 'lldb'
]
packagesAUR = [
  'moonlight-qt', 'mpdris2', 'modrinth-app-git', 'r2modman-bin', 'ddcui'
]
alsa.defaultCard = 'Generic_1'
batModel = 'L22M4PF7'
hibernateResumeOffset = 20038942
cryptrootUUID = '9be53b4a-9e15-4ae7-bb93-0f75875e9bfd'
# /dev/mapper/cryptroot LABEL=arch_os
fstabRootUUID = '89209d7b-bde0-4169-b92e-7b1dd3cbe1bf'
# /dev/nvme0n1p1
fstabBootUUID = '9523-8B3D'
# /dev/mapper/cryptroot LABEL=arch_os
fstabHomeUUID = '89209d7b-bde0-4169-b92e-7b1dd3cbe1bf'
# /dev/mapper/cryptroot LABEL=arch_os
fstabSnapshotsUUID = '89209d7b-bde0-4169-b92e-7b1dd3cbe1bf'
# /dev/mapper/cryptroot LABEL=arch_os
fstabVarLogUUID = '89209d7b-bde0-4169-b92e-7b1dd3cbe1bf'
wirelessAdapterName = 'wlp1s0'
SSID = 'Xiaomi_704C_5G'

[[PROTEUSLAPTOP.alsa.pcms]]
name = '!default'
path = 'Generic_1,0'

[[PROTEUSLAPTOP.alsa.pcms]]
name = 'dhdmi0'
path = 'Generic,3'

[[PROTEUSLAPTOP.alsa.pcms]]
name = 'dhdmi1'
path = 'Generic,7'

[[PROTEUSLAPTOP.alsa.pcms]]
name = 'dhdmi2'
path = 'Generic,8'

[[PROTEUSLAPTOP.alsa.pcms]]
name = 'ddmic'
path = 'acp63,0'

[PROTEUSNOTEBOOK]
installExtra = true
alsa.defaultCard = 'PCH'
hibernateResumeOffset = 30807076
cryptrootUUID = 'b1c2370d-ad25-4fcf-ad93-5b8c19a22e10'
# /dev/mapper/cryptroot LABEL=arch_os
fstabRootUUID = '5e2f7a9c-1198-4135-a9c9-a9cf689f531d'
# /dev/nvme1n1p1
fstabBootUUID = 'D56B-850D'
# /dev/mapper/cryptroot LABEL=arch_os
fstabHomeUUID = '5e2f7a9c-1198-4135-a9c9-a9cf689f531d'
# /dev/mapper/cryptroot LABEL=arch_os
fstabSnapshotsUUID = '5e2f7a9c-1198-4135-a9c9-a9cf689f531d'
# /dev/mapper/cryptroot LABEL=arch_os
fstabVarLogUUID = '5e2f7a9c-1198-4135-a9c9-a9cf689f531d'
wireAdapterName = 'enp46s0'
wirelessAdapterName = 'wlo1'
packagesSpec = [
  'bluez', 'bluez-utils', 'iwd', 'wireless-regdb', 'blueman',
  'intel-ucode', 'vulkan-intel', 'intel-media-driver', 'linux-zen-headers', 'nvidia-open-dkms', 'nvidia-prime', 'lib32-nvidia-utils', 'cockpit-machines', 'cockpit-storaged', 'virt-install', 'qemu', 'dnsmasq', 'dmidecode', 'edk2-ovmf', 'swtpm', 'virt-install', 'intel-undervolt', 'i2pd', 'tor'
]

[[PROTEUSNOTEBOOK.alsa.pcms]]
name = '!default'
path = 'PCH,0'

[[PROTEUSNOTEBOOK.alsa.pcms]]
name = 'dhdmi0'
path = 'PCH,3'

[[PROTEUSNOTEBOOK.alsa.pcms]]
name = 'dhdmi1'
path = 'PCH,7'

[[PROTEUSNOTEBOOK.alsa.pcms]]
name = 'dhdmi2'
path = 'PCH,8'

[[PROTEUSNOTEBOOK.alsa.pcms]]
name = 'dhdmi3'
path = 'PCH,9'

[[PROTEUSNOTEBOOK.alsa.pcms]]
name = 'dnvhdmi0'
path = 'NVidia,3'

[[PROTEUSNOTEBOOK.alsa.pcms]]
name = 'dnvhdmi1'
path = 'NVidia,7'

[[PROTEUSNOTEBOOK.alsa.pcms]]
name = 'dnvhdmi2'
path = 'NVidia,8'

[[PROTEUSNOTEBOOK.alsa.pcms]]
name = 'dnvhdmi3'
path = 'NVidia,9'

[PROTEUSDESKTOP]
hibernateResumeOffset = 1844480
# /dev/mapper/cryptroot LABEL=arch_os
fstabRootUUID = 'ea9d15ae-15de-4acf-9b45-a87400da2b43'
# /dev/nvme0n1p1
fstabBootUUID = '5A7D-FE1E'
# /dev/mapper/cryptroot LABEL=arch_os
fstabHomeUUID = 'ea9d15ae-15de-4acf-9b45-a87400da2b43'
# /dev/mapper/cryptroot LABEL=arch_os
fstabSnapshotsUUID = 'ea9d15ae-15de-4acf-9b45-a87400da2b43'
# /dev/mapper/cryptroot LABEL=arch_os
fstabVarLogUUID = 'ea9d15ae-15de-4acf-9b45-a87400da2b43'
wireAdapterName = 'enp2s0'
packagesSpec = [
  'intel-ucode', 'mesa', 'vulkan-intel', 'docker', 'docker-compose', 'intel-undervolt',
  'lighttpd', 'postgresql'
]
packagesAUR = [
  'libva-intel-driver-hybrid', 'libva-intel-driver-hybrid', 'wsdd2'
]
