[COMMON]
packages.arch = [
  'linux-zen', 'linux-firmware', 'sbctl',
  'base', 'base-devel', 'udisks2', 'rng-tools', 'zram-generator', 'btrfs-progs', 'bash-completion', 'openssh', 'git', 'helix', 'ntfs-3g', 'cifs-utils',
  'bash-language-server', 'marksman', 'taplo', 'texlab', 'python-lsp-server', 'vscode-css-languageserver', 'vscode-json-languageserver', 'yaml-language-server',
  'btop', 'tmux', 'zsh', 'zsh-autosuggestions', 'zsh-syntax-highlighting', 'zsh-history-substring-search', 'compsize', 'p7zip', 'unrar', 'innoextract', 'dust',
  'noto-fonts', 'noto-fonts-cjk', 'noto-fonts-emoji'
]
packages.archExtra = [
  'rsync', 'man', 'tealdeer', 'ripgrep', 'fzf', 'bc', 'usbutils',
  'syncthing', 'hyfetch',
  'pipewire', 'wireplumber', 'pipewire-alsa', 'pipewire-pulse', 'libpulse', 'alsa-utils', 'playerctl',
  'libva-mesa-driver', 'libva-utils', 'vulkan-tools',
  'ly', 'hyprland', 'hypridle', 'hyprpaper', 'waybar', 'mako', 'xdg-desktop-portal-hyprland', 'rofi-wayland', 'cliphist', 'polkit-gnome', 'power-profiles-daemon', 'qt6ct', 'alacritty', 'grim', 'slurp', 'doublecmd-qt6', 'ffmpegthumbnailer', 'gvfs', 'gvfs-mtp', 'imv',
  'fcitx5-im', 'fcitx5-mozc', 'fcitx5-chewing', 'fcitx5-chinese-addons', 'fcitx5-pinyin-zhwiki',
  'texlive-latexextra', 'texlive-binextra', 'texlive-mathscience', 'texlive-xetex',
  'firefox', 'profile-sync-daemon', 'mpv', 'zathura', 'zathura-pdf-poppler', 'keepassxc',
  'img2pdf', 'gimp', 'obs-studio',
  'steam', 'lutris', 'telegram-desktop',
]

[PROTEUSLAPTOP]
installExtra = true
packagesSpec = [
  'amd-ucode', 'bluez', 'bluez-utils', 'iwd', 'wireless-regdb', 'mesa', 'vulkan-radeon',
  ]
mainUser = 'proteus'
aurChrootPath = '/mnt/aur_chroot'
packagesAUR = [
  'paru', 'hyprlock-git', 'sing-box', 'ttf-material-design-icons-extended', 'fcitx5-pinyin-moegirl', 'anki',
  'protontricks', 'yazi'
]
alsa.defaultCard = 'Generic_1'
batModel = 'L22M4PF7'
hibernateResumeOffset = 20038942
wirelessAdapterName = 'wlp1s0'

[[PROTEUSLAPTOP.alsa.pcms]]
name = '!default'
path = 'Generic_1,0'

[[PROTEUSLAPTOP.alsa.pcms]]
name = 'dhdmi0'
path = 'Generic,3'

[[PROTEUSLAPTOP.alsa.pcms]]
name = 'dhdmi1'
path = 'Generic,7'

[[PROTEUSLAPTOP.alsa.pcms]]
name = 'dhdmi2'
path = 'Generic,8'

[[PROTEUSLAPTOP.alsa.pcms]]
name = 'ddmic'
path = 'acp63,0'
